language: c

matrix:
  include:

  # OSX / Clang

  - os: osx
    osx_image: xcode6.4

  - os: osx
    osx_image: xcode7.3

  # Linux / GCC

  - os: linux
    compiler: gcc
    env: COMPILER=gcc-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-4.9', 'ninja-build']

  - os: linux
    compiler: gcc
    env: COMPILER=gcc-5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-5', 'ninja-build']

  - os: linux
    compiler: gcc
    env: COMPILER=gcc-6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-6', 'ninja-build']

  - os: linux
    compiler: gcc
    env: COMPILER=gcc-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-7', 'ninja-build']

  # Linux / Clang

  - os: linux
    compiler: clang
    env: COMPILER=clang-3.5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
        packages: ['check', 'gcc-6', 'clang-3.5', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-3.6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
        packages: ['check', 'gcc-6', 'clang-3.6', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-3.7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
        packages: ['check', 'gcc-6', 'clang-3.7', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-3.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-6', 'clang-3.8', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-3.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['check', 'gcc-6', 'clang-3.9', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-4.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
        packages: ['check', 'gcc-6', 'clang-4.0', 'ninja-build']

  - os: linux
    compiler: clang
    env: COMPILER=clang-5.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['check', 'gcc-6', 'clang-5.0', 'ninja-build']

script:
  # get check and Ninja (only for systems with brew - macOS)
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install check ninja
       cmake --version
     fi

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - autoreconf -iv
  - ./configure && make && make check
